require("98prabowo.plugins-setup")
require("98prabowo.core.options")
require("98prabowo.core.keymaps")
require("98prabowo.themes.colorscheme")
require("98prabowo.lsp.perl")
require("98prabowo.lsp.python")
require("98prabowo.lsp.ruby")
